package presentacion;

import java.awt.Color;
import java.awt.Component;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author ASUS
 */
public class Juego extends javax.swing.JFrame {

    private JuegoController control;
    private Modelo modelo;
    
    public Juego(Modelo modelo) {
        this.modelo = modelo;
        initComponents();
        llenarMatrizTablero();
        capturarEventos();        
    }
    
    public JuegoController getControl() {
        if(control == null){
            control = new JuegoController(modelo);
        }return control;
    }   
    
    private void capturarEventos(){
        btnTomarFicha.addActionListener(getControl());
        btnIniciarJuego.addActionListener(getControl());
        btnVerificar.addActionListener(getControl());
      
        for(Component c: pnlTablero.getComponents()){            
            if(c instanceof JButton){
                ((JButton) c).addActionListener(getControl());
            }
        }
    }    
    
    private void llenarMatrizTablero(){
        for(int i = 0; i < 160; i++)
            pnlTablero.add(new FichaPanel("", Color.BLACK));
    }
    
    //GETTERS

    public JButton getBtnTomarFicha() {
        return btnTomarFicha;
    }

    public JPanel getPnlFichas() {
        return pnlFichas;
    }    

    public JPanel getPnlTablero() {
        return pnlTablero;
    }

    public JButton getBtnIniciarJuego() {
        return btnIniciarJuego;
    }

    public JTextField getTxtUsuario() {
        return txtUsuario;
    }
    
    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public JButton getBtnVerificar() {
        return btnVerificar;
    }
    
    public JLabel getJLabelJug1() {
        return jLabelJug1;
    }

    public JLabel getJLabelJug2() {
        return jLabelJug2;
    }    

    public JLabel getJLabelJug3() {
        return jLabelJug3;
    } 

    public JLabel getJLabelJug4() {
        return jLabelJug4;
    } 
    
    public JButton getBtnImagenJugador1() {
        return btnImagenJugador1;
    } 

    public JButton getBtnImagenJugador2() {
        return btnImagenJugador2;
    }

    public JButton getBtnImagenJugador3() {
        return btnImagenJugador3;
    }

    public JButton getBtnImagenJugador4() {
        return btnImagenJugador4;
    }

    public JPanel getPnlJugadores() {
        return pnlJugadores;
    }

    public JPanel getPnlAcciones() {
        return pnlAcciones;
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnIniciarJuego = new javax.swing.JButton();
        txtUsuario = new javax.swing.JTextField();
        pnlEspera = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        btnCancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        pnlJuego = new javax.swing.JPanel();
        pnlJugadores = new javax.swing.JPanel();
        jLabelJug1 = new javax.swing.JLabel();
        jLabelJug2 = new javax.swing.JLabel();
        jLabelJug3 = new javax.swing.JLabel();
        jLabelJug4 = new javax.swing.JLabel();
        btnImagenJugador2 = new javax.swing.JButton();
        btnImagenJugador1 = new javax.swing.JButton();
        btnImagenJugador4 = new javax.swing.JButton();
        btnImagenJugador3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        containerInferior1 = new javax.swing.JPanel();
        pnlAcciones = new javax.swing.JPanel();
        btnTomarFicha = new javax.swing.JButton();
        btnVerificar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        pnlFichas = new javax.swing.JPanel();
        pnlTablero = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        pnlMenu.setMaximumSize(new java.awt.Dimension(572, 348));
        pnlMenu.setPreferredSize(new java.awt.Dimension(572, 348));
        pnlMenu.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel1.setText("¡Bienvenido al Rummy-q!");
        pnlMenu.add(jLabel1);
        jLabel1.setBounds(110, 10, 380, 40);

        btnIniciarJuego.setText("Iniciar juego");
        pnlMenu.add(btnIniciarJuego);
        btnIniciarJuego.setBounds(231, 100, 100, 30);

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        pnlMenu.add(txtUsuario);
        txtUsuario.setBounds(200, 60, 180, 20);

        getContentPane().add(pnlMenu, "menu");

        pnlEspera.setMaximumSize(new java.awt.Dimension(745, 745));
        pnlEspera.setLayout(new java.awt.BorderLayout());

        jPanel2.setPreferredSize(new java.awt.Dimension(745, 745));

        btnCancelar.setText("Cancelar");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Esperando jugadores");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pnlEspera.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlEspera, "vistaEspera");

        pnlJuego.setPreferredSize(new java.awt.Dimension(745, 745));
        pnlJuego.setLayout(new java.awt.BorderLayout());

        pnlJugadores.setBackground(new java.awt.Color(153, 204, 255));
        pnlJugadores.setPreferredSize(new java.awt.Dimension(200, 200));

        jLabelJug1.setText("Jugador 1");

        jLabelJug2.setText("Jugador 2");

        jLabelJug3.setText("Jugador 3");

        jLabelJug4.setText("Jugador 4");

        btnImagenJugador2.setText("Imgj2");

        btnImagenJugador1.setText("Imgj1");

        btnImagenJugador4.setText("Imgj4");

        btnImagenJugador3.setText("Imgj3");

        javax.swing.GroupLayout pnlJugadoresLayout = new javax.swing.GroupLayout(pnlJugadores);
        pnlJugadores.setLayout(pnlJugadoresLayout);
        pnlJugadoresLayout.setHorizontalGroup(
            pnlJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJugadoresLayout.createSequentialGroup()
                .addGroup(pnlJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnImagenJugador3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnImagenJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnlJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlJugadoresLayout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jLabelJug1))
                            .addGroup(pnlJugadoresLayout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(btnImagenJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(btnImagenJugador4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlJugadoresLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabelJug2))
                    .addGroup(pnlJugadoresLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabelJug3))
                    .addGroup(pnlJugadoresLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabelJug4)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        pnlJugadoresLayout.setVerticalGroup(
            pnlJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJugadoresLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnImagenJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelJug1)
                .addGap(25, 25, 25)
                .addComponent(btnImagenJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelJug2)
                .addGap(23, 23, 23)
                .addComponent(btnImagenJugador3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelJug3)
                .addGap(23, 23, 23)
                .addComponent(btnImagenJugador4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelJug4)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pnlJuego.add(pnlJugadores, java.awt.BorderLayout.LINE_START);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Rummy");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlJuego.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        containerInferior1.setBackground(new java.awt.Color(153, 255, 153));
        containerInferior1.setPreferredSize(new java.awt.Dimension(745, 170));
        containerInferior1.setVerifyInputWhenFocusTarget(false);

        pnlAcciones.setBackground(new java.awt.Color(255, 51, 102));
        pnlAcciones.setLayout(new java.awt.GridLayout(2, 0, 0, 10));

        btnTomarFicha.setText("Tomar ficha");
        pnlAcciones.add(btnTomarFicha);

        btnVerificar.setText("Verificar");
        pnlAcciones.add(btnVerificar);

        pnlFichas.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));
        jScrollPane2.setViewportView(pnlFichas);

        javax.swing.GroupLayout containerInferior1Layout = new javax.swing.GroupLayout(containerInferior1);
        containerInferior1.setLayout(containerInferior1Layout);
        containerInferior1Layout.setHorizontalGroup(
            containerInferior1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerInferior1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlAcciones, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        containerInferior1Layout.setVerticalGroup(
            containerInferior1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAcciones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
            .addGroup(containerInferior1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        pnlJuego.add(containerInferior1, java.awt.BorderLayout.PAGE_END);

        pnlTablero.setLayout(new java.awt.GridLayout(8, 20, 5, 5));
        pnlJuego.add(pnlTablero, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlJuego, "vistaJuego");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnImagenJugador1;
    private javax.swing.JButton btnImagenJugador2;
    private javax.swing.JButton btnImagenJugador3;
    private javax.swing.JButton btnImagenJugador4;
    private javax.swing.JButton btnIniciarJuego;
    private javax.swing.JButton btnTomarFicha;
    private javax.swing.JButton btnVerificar;
    private javax.swing.JPanel containerInferior1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelJug1;
    private javax.swing.JLabel jLabelJug2;
    private javax.swing.JLabel jLabelJug3;
    private javax.swing.JLabel jLabelJug4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlAcciones;
    private javax.swing.JPanel pnlEspera;
    private javax.swing.JPanel pnlFichas;
    private javax.swing.JPanel pnlJuego;
    private javax.swing.JPanel pnlJugadores;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlTablero;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
